<?php

/**
 * Outputs all of the translations strings from the Genesis theme.
 */
function thememix_genesis_translations_strings() {
	return array(
		"Not found, error 404" => __( "Not found, error 404", 'genesis-translations' ),
		"The page you are looking for no longer exists. Perhaps you can return back to the site's <a href=\"%s\">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below." => __( "The page you are looking for no longer exists. Perhaps you can return back to the site's <a href=\"%s\">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below.", 'genesis-translations' ),
		"The page you are looking for no longer exists. Perhaps you can return back to the site's <a href=\"%s\">homepage</a> and see if you can find what you are looking for. Or, you can try finding it with the information below." => __( "The page you are looking for no longer exists. Perhaps you can return back to the site's <a href=\"%s\">homepage</a> and see if you can find what you are looking for. Or, you can try finding it with the information below.", 'genesis-translations' ),
		"Sitemap" => __( "Sitemap", 'genesis-translations' ),
		"This post is password protected. Enter the password to view comments." => __( "This post is password protected. Enter the password to view comments.", 'genesis-translations' ),
		"Reader Interactions" => __( "Reader Interactions", 'genesis-translations' ),
		"Archive Settings" => __( "Archive Settings", 'genesis-translations' ),
		"Archive" => __( "Archive", 'genesis-translations' ),
		"SEO Settings" => __( "SEO Settings", 'genesis-translations' ),
		"Layout Settings" => __( "Layout Settings", 'genesis-translations' ),
		"View the <a href=\"%s\">%s archive</a>." => __( "View the <a href=\"%s\">%s archive</a>.", 'genesis-translations' ),
		"Archive Headline" => __( "Archive Headline", 'genesis-translations' ),
		"Leave empty if you do not want to display a headline." => __( "Leave empty if you do not want to display a headline.", 'genesis-translations' ),
		"Archive Intro Text" => __( "Archive Intro Text", 'genesis-translations' ),
		"Leave empty if you do not want to display any intro text." => __( "Leave empty if you do not want to display any intro text.", 'genesis-translations' ),
		"Custom Document Title" => __( "Custom Document Title", 'genesis-translations' ),
		"Meta Description" => __( "Meta Description", 'genesis-translations' ),
		"Meta Keywords" => __( "Meta Keywords", 'genesis-translations' ),
		"Comma separated list" => __( "Comma separated list", 'genesis-translations' ),
		"Robots Meta Tags:" => __( "Robots Meta Tags:", 'genesis-translations' ),
		"Apply %s to this archive" => __( "Apply %s to this archive", 'genesis-translations' ),
		"Select Layout" => __( "Select Layout", 'genesis-translations' ),
		"Default Layout set in <a href=\"%s\">Theme Settings</a>" => __( "Default Layout set in <a href=\"%s\">Theme Settings</a>", 'genesis-translations' ),
		"Custom Body Class" => __( "Custom Body Class", 'genesis-translations' ),
		"The Archive Headline sets the title seen on the archive page" => __( "The Archive Headline sets the title seen on the archive page", 'genesis-translations' ),
		"The Archive Intro Text sets the text before the archive entries to introduce the content to the viewer." => __( "The Archive Intro Text sets the text before the archive entries to introduce the content to the viewer.", 'genesis-translations' ),
		"The Custom Document Title sets the page title as seen in browsers and search engines. " => __( "The Custom Document Title sets the page title as seen in browsers and search engines. ", 'genesis-translations' ),
		"The Meta description and keywords fill in the meta tags for the archive page. The Meta description is the short text blurb that appear in search engine results.\n " => __( "The Meta description and keywords fill in the meta tags for the archive page. The Meta description is the short text blurb that appear in search engine results.\n ", 'genesis-translations' ),
		"Most search engines do not use Keywords at this time or give them very little consideration; however, it's worth using in case keywords are given greater consideration in the future and also to help guide your content. If the content doesn’t match with your targeted key words, then you may need to consider your content more carefully." => __( "Most search engines do not use Keywords at this time or give them very little consideration; however, it's worth using in case keywords are given greater consideration in the future and also to help guide your content. If the content doesn’t match with your targeted key words, then you may need to consider your content more carefully.", 'genesis-translations' ),
		"The Robots Meta Tags tell search engines how to handle the archive page. Noindex means not to index the page at all, and it will not appear in search results. Nofollow means do not follow any links from this page and noarchive tells them not to make an archive copy of the page." => __( "The Robots Meta Tags tell search engines how to handle the archive page. Noindex means not to index the page at all, and it will not appear in search results. Nofollow means do not follow any links from this page and noarchive tells them not to make an archive copy of the page.", 'genesis-translations' ),
		"This lets you select the layout for the archive page. On most of the child themes you'll see these options:" => __( "This lets you select the layout for the archive page. On most of the child themes you'll see these options:", 'genesis-translations' ),
		"Content Sidebar" => __( "Content Sidebar", 'genesis-translations' ),
		"Sidebar Content" => __( "Sidebar Content", 'genesis-translations' ),
		"Sidebar Content Sidebar" => __( "Sidebar Content Sidebar", 'genesis-translations' ),
		"Content Sidebar Sidebar" => __( "Content Sidebar Sidebar", 'genesis-translations' ),
		"Sidebar Sidebar Content" => __( "Sidebar Sidebar Content", 'genesis-translations' ),
		"Full Width Content" => __( "Full Width Content", 'genesis-translations' ),
		"These options can be extended or limited by the child theme." => __( "These options can be extended or limited by the child theme.", 'genesis-translations' ),
		"The Custom Body Class adds a class to the body tag in the HTML to allow CSS modification exclusively for this post type's archive page." => __( "The Custom Body Class adds a class to the body tag in the HTML to allow CSS modification exclusively for this post type's archive page.", 'genesis-translations' ),
		"When extending Genesis_Customizer_Base, you must create a register method." => __( "When extending Genesis_Customizer_Base, you must create a register method.", 'genesis-translations' ),
		"Use for site title/logo:" => __( "Use for site title/logo:", 'genesis-translations' ),
		"Dynamic Text" => __( "Dynamic Text", 'genesis-translations' ),
		"Image logo" => __( "Image logo", 'genesis-translations' ),
		"Color Scheme" => __( "Color Scheme", 'genesis-translations' ),
		"Select Color Style" => __( "Select Color Style", 'genesis-translations' ),
		"Default" => __( "Default", 'genesis-translations' ),
		"Site Layout" => __( "Site Layout", 'genesis-translations' ),
		"Select Default Layout" => __( "Select Default Layout", 'genesis-translations' ),
		"Breadcrumbs" => __( "Breadcrumbs", 'genesis-translations' ),
		"Breadcrumbs on Homepage" => __( "Breadcrumbs on Homepage", 'genesis-translations' ),
		"Breadcrumbs on Front Page" => __( "Breadcrumbs on Front Page", 'genesis-translations' ),
		"Breadcrumbs on Posts Page" => __( "Breadcrumbs on Posts Page", 'genesis-translations' ),
		"Breadcrumbs on Single Posts" => __( "Breadcrumbs on Single Posts", 'genesis-translations' ),
		"Breadcrumbs on Pages" => __( "Breadcrumbs on Pages", 'genesis-translations' ),
		"Breadcrumbs on Archives" => __( "Breadcrumbs on Archives", 'genesis-translations' ),
		"Breadcrumbs on 404 Page" => __( "Breadcrumbs on 404 Page", 'genesis-translations' ),
		"Breadcrumbs on Attachment/Media" => __( "Breadcrumbs on Attachment/Media", 'genesis-translations' ),
		"Comments and Trackbacks" => __( "Comments and Trackbacks", 'genesis-translations' ),
		"Enable Comments on Posts?" => __( "Enable Comments on Posts?", 'genesis-translations' ),
		"Enable Comments on Pages?" => __( "Enable Comments on Pages?", 'genesis-translations' ),
		"Enable Trackbacks on Posts?" => __( "Enable Trackbacks on Posts?", 'genesis-translations' ),
		"Enable Trackbacks on Pages?" => __( "Enable Trackbacks on Pages?", 'genesis-translations' ),
		"Content Archives" => __( "Content Archives", 'genesis-translations' ),
		"These options will affect any blog listings page, including archive, author, blog, category, search, and tag pages." => __( "These options will affect any blog listings page, including archive, author, blog, category, search, and tag pages.", 'genesis-translations' ),
		"Select one of the following" => __( "Select one of the following", 'genesis-translations' ),
		"Display post content" => __( "Display post content", 'genesis-translations' ),
		"Display post excerpts" => __( "Display post excerpts", 'genesis-translations' ),
		"Limit content to how many characters? (0 for no limit)" => __( "Limit content to how many characters? (0 for no limit)", 'genesis-translations' ),
		"Display the featured image?" => __( "Display the featured image?", 'genesis-translations' ),
		"Featured image size" => __( "Featured image size", 'genesis-translations' ),
		"Featured image alignment" => __( "Featured image alignment", 'genesis-translations' ),
		"- None -" => __( "- None -", 'genesis-translations' ),
		"Left" => __( "Left", 'genesis-translations' ),
		"Right" => __( "Right", 'genesis-translations' ),
		"Post Navigation Type" => __( "Post Navigation Type", 'genesis-translations' ),
		"Previous / Next" => __( "Previous / Next", 'genesis-translations' ),
		"Numeric" => __( "Numeric", 'genesis-translations' ),
		"Genesis - Import/Export" => __( "Genesis - Import/Export", 'genesis-translations' ),
		"Import/Export" => __( "Import/Export", 'genesis-translations' ),
		"This allows you to import or export Genesis Settings." => __( "This allows you to import or export Genesis Settings.", 'genesis-translations' ),
		"This is specific to Genesis settings and does not includes posts, pages, or images, which is what the built-in WordPress import/export menu does." => __( "This is specific to Genesis settings and does not includes posts, pages, or images, which is what the built-in WordPress import/export menu does.", 'genesis-translations' ),
		"It also does not include other settings for plugins, widgets, or post/page/term/user specific settings." => __( "It also does not include other settings for plugins, widgets, or post/page/term/user specific settings.", 'genesis-translations' ),
		"Import" => __( "Import", 'genesis-translations' ),
		"You can import a file you've previously exported. The file name will start with %s followed by one or more strings indicating which settings it contains, finally followed by the date and time it was exported." => __( "You can import a file you've previously exported. The file name will start with %s followed by one or more strings indicating which settings it contains, finally followed by the date and time it was exported.", 'genesis-translations' ),
		"Once you upload an import file, it will automatically overwrite your existing settings." => __( "Once you upload an import file, it will automatically overwrite your existing settings.", 'genesis-translations' ),
		"This cannot be undone" => __( "This cannot be undone", 'genesis-translations' ),
		"Export" => __( "Export", 'genesis-translations' ),
		"You can export your Genesis-related settings to back them up, or copy them to another site. Child themes and plugins may add their own checkboxes to the list. The settings are exported in %s format." => __( "You can export your Genesis-related settings to back them up, or copy them to another site. Child themes and plugins may add their own checkboxes to the list. The settings are exported in %s format.", 'genesis-translations' ),
		"JavaScript Object Notation" => __( "JavaScript Object Notation", 'genesis-translations' ),
		"JSON" => __( "JSON", 'genesis-translations' ),
		"For more information:" => __( "For more information:", 'genesis-translations' ),
		"Get Support" => __( "Get Support", 'genesis-translations' ),
		"Link opens in a new window." => __( "Link opens in a new window.", 'genesis-translations' ),
		"Genesis Snippets" => __( "Genesis Snippets", 'genesis-translations' ),
		"Genesis Tutorials" => __( "Genesis Tutorials", 'genesis-translations' ),
		"Import Genesis Settings File" => __( "Import Genesis Settings File", 'genesis-translations' ),
		"Upload the data file (%s) from your computer and we'll import your settings." => __( "Upload the data file (%s) from your computer and we'll import your settings.", 'genesis-translations' ),
		"Choose the file from your computer and click \"Upload file and Import\"" => __( "Choose the file from your computer and click \"Upload file and Import\"", 'genesis-translations' ),
		"Upload File (Maximum Size: %s): " => __( "Upload File (Maximum Size: %s): ", 'genesis-translations' ),
		"Upload File and Import" => __( "Upload File and Import", 'genesis-translations' ),
		"Export Genesis Settings File" => __( "Export Genesis Settings File", 'genesis-translations' ),
		"When you click the button below, Genesis will generate a data file (%s) for you to save to your computer." => __( "When you click the button below, Genesis will generate a data file (%s) for you to save to your computer.", 'genesis-translations' ),
		"Once you have saved the download file, you can use the import function on another site to import this data." => __( "Once you have saved the download file, you can use the import function on another site to import this data.", 'genesis-translations' ),
		"Download Export File" => __( "Download Export File", 'genesis-translations' ),
		"Settings successfully imported." => __( "Settings successfully imported.", 'genesis-translations' ),
		"There was a problem importing your settings. Please try again." => __( "There was a problem importing your settings. Please try again.", 'genesis-translations' ),
		"Theme Settings" => __( "Theme Settings", 'genesis-translations' ),
		"No export options available." => __( "No export options available.", 'genesis-translations' ),
		"Theme SEO Settings" => __( "Theme SEO Settings", 'genesis-translations' ),
		"Document Title" => __( "Document Title", 'genesis-translations' ),
		"Characters Used: %s" => __( "Characters Used: %s", 'genesis-translations' ),
		"Canonical URL" => __( "Canonical URL", 'genesis-translations' ),
		"Read more about" => __( "Read more about", 'genesis-translations' ),
		"Custom Canonical URL" => __( "Custom Canonical URL", 'genesis-translations' ),
		"Custom Redirect URL" => __( "Custom Redirect URL", 'genesis-translations' ),
		"Robots Meta Settings" => __( "Robots Meta Settings", 'genesis-translations' ),
		"Apply %s to this post/page" => __( "Apply %s to this post/page", 'genesis-translations' ),
		"Scripts" => __( "Scripts", 'genesis-translations' ),
		"Page-specific Scripts" => __( "Page-specific Scripts", 'genesis-translations' ),
		"Suitable for custom tracking, conversion or other page-specific script. Must include %s tags." => __( "Suitable for custom tracking, conversion or other page-specific script. Must include %s tags.", 'genesis-translations' ),
		"Custom Post Class" => __( "Custom Post Class", 'genesis-translations' ),
		"Genesis - SEO Settings" => __( "Genesis - SEO Settings", 'genesis-translations' ),
		"Save Settings" => __( "Save Settings", 'genesis-translations' ),
		"Reset Settings" => __( "Reset Settings", 'genesis-translations' ),
		"Settings saved." => __( "Settings saved.", 'genesis-translations' ),
		"Settings reset." => __( "Settings reset.", 'genesis-translations' ),
		"Error saving settings." => __( "Error saving settings.", 'genesis-translations' ),
		"Genesis SEO (search engine optimization) is polite, and will disable itself when most popular SEO plugins (e.g., All-in-One SEO, WordPress SEO, etc.) are active." => __( "Genesis SEO (search engine optimization) is polite, and will disable itself when most popular SEO plugins (e.g., All-in-One SEO, WordPress SEO, etc.) are active.", 'genesis-translations' ),
		"If you don’t see an SEO Settings sub menu, then you probably have another SEO plugin active." => __( "If you don’t see an SEO Settings sub menu, then you probably have another SEO plugin active.", 'genesis-translations' ),
		"If you see the menu, then opening that menu item will let you set the General SEO settings for your site." => __( "If you see the menu, then opening that menu item will let you set the General SEO settings for your site.", 'genesis-translations' ),
		"Each page, post, and term will have its own SEO settings as well. The default settings are recommended for most users. If you wish to adjust your SEO settings, the boxes include internal descriptions." => __( "Each page, post, and term will have its own SEO settings as well. The default settings are recommended for most users. If you wish to adjust your SEO settings, the boxes include internal descriptions.", 'genesis-translations' ),
		"Below you'll find a few succinct notes on the options for each box:" => __( "Below you'll find a few succinct notes on the options for each box:", 'genesis-translations' ),
		"Doctitle Settings" => __( "Doctitle Settings", 'genesis-translations' ),
		"<strong>Append Site Description</strong> will insert the site description from your General Settings after the title on your home page." => __( "<strong>Append Site Description</strong> will insert the site description from your General Settings after the title on your home page.", 'genesis-translations' ),
		"<strong>Append Site Name</strong> will put the site name from the General Settings after the title on inner page." => __( "<strong>Append Site Name</strong> will put the site name from the General Settings after the title on inner page.", 'genesis-translations' ),
		"<strong>Doctitle Append Location</strong> determines which side of the title to add the previously mentioned items." => __( "<strong>Doctitle Append Location</strong> determines which side of the title to add the previously mentioned items.", 'genesis-translations' ),
		"The <strong>Doctitle Separator</strong> is the character that will go between the title and appended text." => __( "The <strong>Doctitle Separator</strong> is the character that will go between the title and appended text.", 'genesis-translations' ),
		"Homepage Settings" => __( "Homepage Settings", 'genesis-translations' ),
		"These are the homepage specific SEO settings. Note: these settings will not apply if a static page is set as the front page. If you're using a static WordPress page as your hompage, you'll need to set the SEO settings on that particular page." => __( "These are the homepage specific SEO settings. Note: these settings will not apply if a static page is set as the front page. If you're using a static WordPress page as your hompage, you'll need to set the SEO settings on that particular page.", 'genesis-translations' ),
		"You can also specify if the Site Title, Description, or your own custom text should be wrapped in an &lt;h1&gt; tag (the primary heading in HTML)." => __( "You can also specify if the Site Title, Description, or your own custom text should be wrapped in an &lt;h1&gt; tag (the primary heading in HTML).", 'genesis-translations' ),
		"To add custom text you'll have to either edit a php file, or use a text widget on a widget enabled homepage." => __( "To add custom text you'll have to either edit a php file, or use a text widget on a widget enabled homepage.", 'genesis-translations' ),
		'The home doctitle sets what will appear within the %1$s tags (unseen in the browser) for the home page.' => __( 'The home doctitle sets what will appear within the %1$s tags (unseen in the browser) for the home page.', 'genesis-translations' ),
		"The home META description and keywords fill in the meta tags for the home page. The META description is the short text blurb that appear in search engine results." => __( "The home META description and keywords fill in the meta tags for the home page. The META description is the short text blurb that appear in search engine results.", 'genesis-translations' ),
		"The Homepage Robots Meta Tags tell search engines how to handle the homepage. Noindex means not to index the page at all, and it will not appear in search results. Nofollow means do not follow any links from this page and noarchive tells them not to make an archive copy of the page." => __( "The Homepage Robots Meta Tags tell search engines how to handle the homepage. Noindex means not to index the page at all, and it will not appear in search results. Nofollow means do not follow any links from this page and noarchive tells them not to make an archive copy of the page.", 'genesis-translations' ),
		"Document Head Settings" => __( "Document Head Settings", 'genesis-translations' ),
		"The Relationship Link Tags are tags added by WordPress that currently have no SEO value but slow your site load down. They're disabled by default, but if you have a specific need&#8212;for a plugin or other non typical use&#8212;then you can enable as needed here." => __( "The Relationship Link Tags are tags added by WordPress that currently have no SEO value but slow your site load down. They're disabled by default, but if you have a specific need&#8212;for a plugin or other non typical use&#8212;then you can enable as needed here.", 'genesis-translations' ),
		"You can also add support for Windows Live Writer if you use software that supports this and include a shortlink tag if this is required by any third party service." => __( "You can also add support for Windows Live Writer if you use software that supports this and include a shortlink tag if this is required by any third party service.", 'genesis-translations' ),
		"Noarchive and noindex are explained in the home settings. Here you can select what other parts of the site to apply these options to." => __( "Noarchive and noindex are explained in the home settings. Here you can select what other parts of the site to apply these options to.", 'genesis-translations' ),
		"At least one archive should be indexed, but indexing multiple archives will typically result in a duplicate content penalization (multiple pages with identical content look manipulative to search engines)." => __( "At least one archive should be indexed, but indexing multiple archives will typically result in a duplicate content penalization (multiple pages with identical content look manipulative to search engines).", 'genesis-translations' ),
		"For most sites either the home page or blog page (using the blog template) will serve as this index which is why the default is not to index categories, tags, authors, dates, or searches." => __( "For most sites either the home page or blog page (using the blog template) will serve as this index which is why the default is not to index categories, tags, authors, dates, or searches.", 'genesis-translations' ),
		"Sitewide Settings" => __( "Sitewide Settings", 'genesis-translations' ),
		"Section Headings" => __( "Section Headings", 'genesis-translations' ),
		"Use semantic HTML5 page and section headings throughout site?" => __( "Use semantic HTML5 page and section headings throughout site?", 'genesis-translations' ),
		"Add site name to %s on inner pages?" => __( "Add site name to %s on inner pages?", 'genesis-translations' ),
		"Document Title Separator:" => __( "Document Title Separator:", 'genesis-translations' ),
		"If the title consists of two parts (original title and optional addition), then the separator will go in between them." => __( "If the title consists of two parts (original title and optional addition), then the separator will go in between them.", 'genesis-translations' ),
		"Document Title Order" => __( "Document Title Order", 'genesis-translations' ),
		"Additions on left" => __( "Additions on left", 'genesis-translations' ),
		"Additions on right" => __( "Additions on right", 'genesis-translations' ),
		"Determines which side the added title text will go on." => __( "Determines which side the added title text will go on.", 'genesis-translations' ),
		"Primary Title %s" => __( "Primary Title %s", 'genesis-translations' ),
		"Site Title" => __( "Site Title", 'genesis-translations' ),
		"Site Description (Tagline)" => __( "Site Description (Tagline)", 'genesis-translations' ),
		"I'll manually wrap my own text on the homepage" => __( "I'll manually wrap my own text on the homepage", 'genesis-translations' ),
		"Document Title:" => __( "Document Title:", 'genesis-translations' ),
		"If you leave the document title field blank, your site&#8217;s title will be used instead." => __( "If you leave the document title field blank, your site&#8217;s title will be used instead.", 'genesis-translations' ),
		"Add site description (tagline) to %s on home page?" => __( "Add site description (tagline) to %s on home page?", 'genesis-translations' ),
		"Meta Description:" => __( "Meta Description:", 'genesis-translations' ),
		"The meta description can be used to determine the text used under the title on search engine results pages." => __( "The meta description can be used to determine the text used under the title on search engine results pages.", 'genesis-translations' ),
		"Meta Keywords:" => __( "Meta Keywords:", 'genesis-translations' ),
		"Keywords are generally ignored by Search Engines." => __( "Keywords are generally ignored by Search Engines.", 'genesis-translations' ),
		"Apply %s to the homepage?" => __( "Apply %s to the homepage?", 'genesis-translations' ),
		'By default, WordPress places several tags in your document %1$s. Most of these tags are completely unnecessary, and provide no <abbr title=\"Search engine optimization\">SEO</abbr> value whatsoever; they just make your site slower to load. Choose which tags you would like included in your document %1$s. If you do not know what something is, leave it unchecked.' => __( 'By default, WordPress places several tags in your document %1$s. Most of these tags are completely unnecessary, and provide no <abbr title=\"Search engine optimization\">SEO</abbr> value whatsoever; they just make your site slower to load. Choose which tags you would like included in your document %1$s. If you do not know what something is, leave it unchecked.', 'genesis-translations' ),
		"Relationship Link Tags" => __( "Relationship Link Tags", 'genesis-translations' ),
		"Adjacent Posts %s link tags" => __( "Adjacent Posts %s link tags", 'genesis-translations' ),
		"Windows Live Writer" => __( "Windows Live Writer", 'genesis-translations' ),
		"Include Windows Live Writer Support Tag?" => __( "Include Windows Live Writer Support Tag?", 'genesis-translations' ),
		"Shortlink Tag" => __( "Shortlink Tag", 'genesis-translations' ),
		"Include Shortlink tag?" => __( "Include Shortlink tag?", 'genesis-translations' ),
		"<span class=\"genesis-admin-note\">Note:</span> The shortlink tag might have some use for 3rd party service discoverability, but it has no <abbr title=\"Search engine optimization\">SEO</abbr> value whatsoever." => __( "<span class=\"genesis-admin-note\">Note:</span> The shortlink tag might have some use for 3rd party service discoverability, but it has no <abbr title=\"Search engine optimization\">SEO</abbr> value whatsoever.", 'genesis-translations' ),
		"Indexing" => __( "Indexing", 'genesis-translations' ),
		"Apply %s to Category Archives?" => __( "Apply %s to Category Archives?", 'genesis-translations' ),
		"Apply %s to Tag Archives?" => __( "Apply %s to Tag Archives?", 'genesis-translations' ),
		"Apply %s to Author Archives?" => __( "Apply %s to Author Archives?", 'genesis-translations' ),
		"Apply %s to Date Archives?" => __( "Apply %s to Date Archives?", 'genesis-translations' ),
		"Apply %s to Search Archives?" => __( "Apply %s to Search Archives?", 'genesis-translations' ),
		"Archiving" => __( "Archiving", 'genesis-translations' ),
		"Apply %s to Entire Site?" => __( "Apply %s to Entire Site?", 'genesis-translations' ),
		"Directories" => __( "Directories", 'genesis-translations' ),
		"Apply %s to your site?" => __( "Apply %s to your site?", 'genesis-translations' ),
		"Robots Meta" => __( "Robots Meta", 'genesis-translations' ),
		"Apply %s to this archive?" => __( "Apply %s to this archive?", 'genesis-translations' ),
		"Choose Layout" => __( "Choose Layout", 'genesis-translations' ),
		"Follow me on Twitter" => __( "Follow me on Twitter", 'genesis-translations' ),
		"Your Theme Settings provides control over how the theme works. You will be able to control a lot of common and even advanced features from this menu. Some child themes may add additional menu items to this list, including the ability to select different color schemes or set theme specific features such as a slider. Each of the boxes can be collapsed by clicking the box header and expanded by doing the same. They can also be dragged into any order you desire or even hidden by clicking on \"Screen Options\" in the top right of the screen and \"unchecking\" the boxes you do not want to see. Below you'll find the items common to every child theme &#x02026;" => __( "Your Theme Settings provides control over how the theme works. You will be able to control a lot of common and even advanced features from this menu. Some child themes may add additional menu items to this list, including the ability to select different color schemes or set theme specific features such as a slider. Each of the boxes can be collapsed by clicking the box header and expanded by doing the same. They can also be dragged into any order you desire or even hidden by clicking on \"Screen Options\" in the top right of the screen and \"unchecking\" the boxes you do not want to see. Below you'll find the items common to every child theme &#x02026;", 'genesis-translations' ),
		"Information" => __( "Information", 'genesis-translations' ),
		"The information box allows you to see the current Genesis theme information and display if desired." => __( "The information box allows you to see the current Genesis theme information and display if desired.", 'genesis-translations' ),
		"Normally, this should be unchecked. You can also set to enable automatic updates." => __( "Normally, this should be unchecked. You can also set to enable automatic updates.", 'genesis-translations' ),
		"This does not mean the updates happen automatically without your permission; it will just notify you that an update is available. You must select it to perform the update." => __( "This does not mean the updates happen automatically without your permission; it will just notify you that an update is available. You must select it to perform the update.", 'genesis-translations' ),
		"If you provide an email address and select to notify that email address when the update is available, your site will email you when the update can be performed.No, updates only affect files being updated." => __( "If you provide an email address and select to notify that email address when the update is available, your site will email you when the update can be performed.No, updates only affect files being updated.", 'genesis-translations' ),
		"Custom Feeds" => __( "Custom Feeds", 'genesis-translations' ),
		"If you use Feedburner to handle your rss feed(s) you can use this function to set your site's native feed to redirect to your Feedburner feed." => __( "If you use Feedburner to handle your rss feed(s) you can use this function to set your site's native feed to redirect to your Feedburner feed.", 'genesis-translations' ),
		"By filling in the feed links calling for the main site feed, it will display as a link to Feedburner." => __( "By filling in the feed links calling for the main site feed, it will display as a link to Feedburner.", 'genesis-translations' ),
		"By checking the \"Redirect Feed\" box, all traffic to default feed links will be redirected to the Feedburner link instead." => __( "By checking the \"Redirect Feed\" box, all traffic to default feed links will be redirected to the Feedburner link instead.", 'genesis-translations' ),
		"Default Layout" => __( "Default Layout", 'genesis-translations' ),
		"This lets you select the default layout for your entire site. On most of the child themes you'll see these options:" => __( "This lets you select the default layout for your entire site. On most of the child themes you'll see these options:", 'genesis-translations' ),
		"These options can be extended or limited by the child theme. Additionally, many of the child themes do not allow different layouts on the home page as they have been designed for a specific home page layout." => __( "These options can be extended or limited by the child theme. Additionally, many of the child themes do not allow different layouts on the home page as they have been designed for a specific home page layout.", 'genesis-translations' ),
		"This layout can also be overridden in the post/page/term layout options on each post/page/term." => __( "This layout can also be overridden in the post/page/term layout options on each post/page/term.", 'genesis-translations' ),
		"Header" => __( "Header", 'genesis-translations' ),
		"The <strong>Dynamic text</strong> option will use the Site Title and Site Description from your site's settings in your header." => __( "The <strong>Dynamic text</strong> option will use the Site Title and Site Description from your site's settings in your header.", 'genesis-translations' ),
		"The <strong>Image logo</strong> option will use a logo image file in the header instead of the site's title and description. This setting adds a .header-image class to your site, allowing you to specify the header image in your child theme's style.css. By default, the logo can be saved as logo.png and saved to the images folder of your child theme." => __( "The <strong>Image logo</strong> option will use a logo image file in the header instead of the site's title and description. This setting adds a .header-image class to your site, allowing you to specify the header image in your child theme's style.css. By default, the logo can be saved as logo.png and saved to the images folder of your child theme.", 'genesis-translations' ),
		"Navigation" => __( "Navigation", 'genesis-translations' ),
		"The Primary Navigation Extras typically display on the right side of your Primary Navigation menu." => __( "The Primary Navigation Extras typically display on the right side of your Primary Navigation menu.", 'genesis-translations' ),
		"Today's date displays the current date" => __( "Today's date displays the current date", 'genesis-translations' ),
		"RSS feed link displays a link to the RSS feed for your site that a reader can use to subscribe to your site using the feedreader of their choice." => __( "RSS feed link displays a link to the RSS feed for your site that a reader can use to subscribe to your site using the feedreader of their choice.", 'genesis-translations' ),
		"Search form displays a small search form utilizing the WordPress search functionality." => __( "Search form displays a small search form utilizing the WordPress search functionality.", 'genesis-translations' ),
		"Twitter link displays a link to your Twitter profile, as indicated in Twitter ID setting. Enter only your user name in this setting." => __( "Twitter link displays a link to your Twitter profile, as indicated in Twitter ID setting. Enter only your user name in this setting.", 'genesis-translations' ),
		"This box lets you define where the \"Breadcrumbs\" display. The Breadcrumb is the navigation tool that displays where a visitor is on the site at any given moment." => __( "This box lets you define where the \"Breadcrumbs\" display. The Breadcrumb is the navigation tool that displays where a visitor is on the site at any given moment.", 'genesis-translations' ),
		"This allows a site wide decision on whether comments and trackbacks (notifications when someone links to your page) are enabled for posts and pages." => __( "This allows a site wide decision on whether comments and trackbacks (notifications when someone links to your page) are enabled for posts and pages.", 'genesis-translations' ),
		"If you enable comments or trackbacks here, it can be disabled on an individual post or page. If you disable here, they cannot be enabled on an individual post or page." => __( "If you enable comments or trackbacks here, it can be disabled on an individual post or page. If you disable here, they cannot be enabled on an individual post or page.", 'genesis-translations' ),
		"In the Genesis Theme Settings you may change the site wide Content Archives options to control what displays in the site's Archives." => __( "In the Genesis Theme Settings you may change the site wide Content Archives options to control what displays in the site's Archives.", 'genesis-translations' ),
		"Archives include any pages using the blog template, category pages, tag pages, date archive, author archives, and the latest posts if there is no custom home page." => __( "Archives include any pages using the blog template, category pages, tag pages, date archive, author archives, and the latest posts if there is no custom home page.", 'genesis-translations' ),
		"The first option allows you to display the post content or the post excerpt. The Display post content setting will display the entire post including HTML code up to the <!--more--> tag if used (this is HTML for the comment tag that is not displayed in the browser)." => __( "The first option allows you to display the post content or the post excerpt. The Display post content setting will display the entire post including HTML code up to the <!--more--> tag if used (this is HTML for the comment tag that is not displayed in the browser).", 'genesis-translations' ),
		"It may also be coupled with the second field \"Limit content to [___] characters\" to limit the content to a specific number of letters or spaces. This will strip any HTML, but allows for more precise and easily changed lengths than the excerpt." => __( "It may also be coupled with the second field \"Limit content to [___] characters\" to limit the content to a specific number of letters or spaces. This will strip any HTML, but allows for more precise and easily changed lengths than the excerpt.", 'genesis-translations' ),
		"The Display post excerpt setting will display the first 55 words of the post after also stripping any included HTML or the manual/custom excerpt added in the post edit screen." => __( "The Display post excerpt setting will display the first 55 words of the post after also stripping any included HTML or the manual/custom excerpt added in the post edit screen.", 'genesis-translations' ),
		"The 'Include post image?' setting allows you to show a thumbnail of the first attached image or currently set featured image." => __( "The 'Include post image?' setting allows you to show a thumbnail of the first attached image or currently set featured image.", 'genesis-translations' ),
		"This option should not be used with the post content unless the content is limited to avoid duplicate images." => __( "This option should not be used with the post content unless the content is limited to avoid duplicate images.", 'genesis-translations' ),
		"The 'Image Size' list is populated by the available image sizes defined in the theme." => __( "The 'Image Size' list is populated by the available image sizes defined in the theme.", 'genesis-translations' ),
		"Post Navigation Technique allows you to select one of three navigation methods." => __( "Post Navigation Technique allows you to select one of three navigation methods.", 'genesis-translations' ),
		"Blog Page" => __( "Blog Page", 'genesis-translations' ),
		"This works with the Blog Template, which is a page template that shows your latest posts. It's what people see when they land on your homepage." => __( "This works with the Blog Template, which is a page template that shows your latest posts. It's what people see when they land on your homepage.", 'genesis-translations' ),
		"In the General Settings you can select a specific category to display from the drop down menu, and exclude categories by ID, or even select how many posts you'd like to display on this page." => __( "In the General Settings you can select a specific category to display from the drop down menu, and exclude categories by ID, or even select how many posts you'd like to display on this page.", 'genesis-translations' ),
		"There are some special features of the Blog Template that allow you to specify which category to show on each page using the template, which is helpful if you have a \"News\" category (or something else) that you want to display separately." => __( "There are some special features of the Blog Template that allow you to specify which category to show on each page using the template, which is helpful if you have a \"News\" category (or something else) that you want to display separately.", 'genesis-translations' ),
		"You can find more on this feature in the <a href=\"%s\" target=\"_blank\">How to Add a Post Category Page tutorial.</a>" => __( "You can find more on this feature in the <a href=\"%s\" target=\"_blank\">How to Add a Post Category Page tutorial.</a>", 'genesis-translations' ),
		"Header and Footer Scripts" => __( "Header and Footer Scripts", 'genesis-translations' ),
		'This provides you with two fields that will output to the %1$s element of your site and just before the %2$s tag. These will appear on every page of the site and are a great way to add analytic code and other scripts. You cannot use PHP in these fields. If you need to use PHP then you should look into the Genesis Simple Hooks plugin.' => __( 'This provides you with two fields that will output to the %1$s element of your site and just before the %2$s tag. These will appear on every page of the site and are a great way to add analytic code and other scripts. You cannot use PHP in these fields. If you need to use PHP then you should look into the Genesis Simple Hooks plugin.', 'genesis-translations' ),
		"How Home Pages Work" => __( "How Home Pages Work", 'genesis-translations' ),
		"Most Genesis child themes include a custom home page." => __( "Most Genesis child themes include a custom home page.", 'genesis-translations' ),
		"To use this type of home page, make sure your latest posts are set to show on the front page. You can setup a page with the Blog page template to show a blog style list of your latest posts on another page." => __( "To use this type of home page, make sure your latest posts are set to show on the front page. You can setup a page with the Blog page template to show a blog style list of your latest posts on another page.", 'genesis-translations' ),
		"This home page is typically setup via widgets in the sidebars for the home page. This can be accessed via the Widgets menu item under Appearance." => __( "This home page is typically setup via widgets in the sidebars for the home page. This can be accessed via the Widgets menu item under Appearance.", 'genesis-translations' ),
		"Child themes that include this type of home page typically include additional theme-specific tutorials which can be accessed via a sticky post at the top of that child theme support forum." => __( "Child themes that include this type of home page typically include additional theme-specific tutorials which can be accessed via a sticky post at the top of that child theme support forum.", 'genesis-translations' ),
		"If your theme uses a custom home page and you want to show the latest posts in a blog format, do not use the blog template. Instead, you need to rename the home.php file to home-old.php instead." => __( "If your theme uses a custom home page and you want to show the latest posts in a blog format, do not use the blog template. Instead, you need to rename the home.php file to home-old.php instead.", 'genesis-translations' ),
		"Another common home page is the \"blog\" type home page, which is common to most of the free child themes. This shows your latest posts and requires no additional setup." => __( "Another common home page is the \"blog\" type home page, which is common to most of the free child themes. This shows your latest posts and requires no additional setup.", 'genesis-translations' ),
		"The third type of home page is the new dynamic home page. This is common on the newest child themes. It will show your latest posts in a blog type listing unless you put widgets into the home page sidebars." => __( "The third type of home page is the new dynamic home page. This is common on the newest child themes. It will show your latest posts in a blog type listing unless you put widgets into the home page sidebars.", 'genesis-translations' ),
		"This setup is preferred because it makes it easier to show a blog on the front page (no need to rename the home.php file) and does not have the confusion of no content on the home page when the theme is initially installed." => __( "This setup is preferred because it makes it easier to show a blog on the front page (no need to rename the home.php file) and does not have the confusion of no content on the home page when the theme is initially installed.", 'genesis-translations' ),
		"Home Pages" => __( "Home Pages", 'genesis-translations' ),
		"Color Style" => __( "Color Style", 'genesis-translations' ),
		"Blog Page Template" => __( "Blog Page Template", 'genesis-translations' ),
		"Version" => __( "Version", 'genesis-translations' ),
		"Released:" => __( "Released:", 'genesis-translations' ),
		"This can be helpful for diagnosing problems with your theme when seeking assistance in the <a href=\"%s\" target=\"_blank\">support forums</a>." => __( "This can be helpful for diagnosing problems with your theme when seeking assistance in the <a href=\"%s\" target=\"_blank\">support forums</a>.", 'genesis-translations' ),
		"Updates" => __( "Updates", 'genesis-translations' ),
		"Enable Automatic Updates" => __( "Enable Automatic Updates", 'genesis-translations' ),
		"Email address" => __( "Email address", 'genesis-translations' ),
		"If you provide an email address above, you will be notified via email when a new version of Genesis is available." => __( "If you provide an email address above, you will be notified via email when a new version of Genesis is available.", 'genesis-translations' ),
		"Color Style:" => __( "Color Style:", 'genesis-translations' ),
		"Please select the color style from the drop down list and save your settings." => __( "Please select the color style from the drop down list and save your settings.", 'genesis-translations' ),
		"Enter your custom feed URL:" => __( "Enter your custom feed URL:", 'genesis-translations' ),
		"Redirect Custom Feed?" => __( "Redirect Custom Feed?", 'genesis-translations' ),
		"Enter your custom comments feed URL:" => __( "Enter your custom comments feed URL:", 'genesis-translations' ),
		"Redirect Custom Comments Feed?" => __( "Redirect Custom Comments Feed?", 'genesis-translations' ),
		"If your custom feed(s) are not handled by Feedblitz or Feedburner, do not use the redirect options." => __( "If your custom feed(s) are not handled by Feedblitz or Feedburner, do not use the redirect options.", 'genesis-translations' ),
		"Dynamic text" => __( "Dynamic text", 'genesis-translations' ),
		"Superfish" => __( "Superfish", 'genesis-translations' ),
		"Load Superfish Script?" => __( "Load Superfish Script?", 'genesis-translations' ),
		"Primary Navigation Extras" => __( "Primary Navigation Extras", 'genesis-translations' ),
		"In order to view the Primary navigation menu settings, you must build a <a href=\"%s\">custom menu</a>, then assign it to the Primary Menu Location." => __( "In order to view the Primary navigation menu settings, you must build a <a href=\"%s\">custom menu</a>, then assign it to the Primary Menu Location.", 'genesis-translations' ),
		"None" => __( "None", 'genesis-translations' ),
		"Today's date" => __( "Today's date", 'genesis-translations' ),
		"RSS feed links" => __( "RSS feed links", 'genesis-translations' ),
		"Search form" => __( "Search form", 'genesis-translations' ),
		"Twitter link" => __( "Twitter link", 'genesis-translations' ),
		"Enter Twitter ID:" => __( "Enter Twitter ID:", 'genesis-translations' ),
		"Twitter Link Text:" => __( "Twitter Link Text:", 'genesis-translations' ),
		"Enable Breadcrumbs on:" => __( "Enable Breadcrumbs on:", 'genesis-translations' ),
		"Front Page" => __( "Front Page", 'genesis-translations' ),
		"Posts Page" => __( "Posts Page", 'genesis-translations' ),
		"Homepage" => __( "Homepage", 'genesis-translations' ),
		"Single Posts" => __( "Single Posts", 'genesis-translations' ),
		"Pages" => __( "Pages", 'genesis-translations' ),
		"Archives" => __( "Archives", 'genesis-translations' ),
		"404 Page" => __( "404 Page", 'genesis-translations' ),
		"Attachment/Media" => __( "Attachment/Media", 'genesis-translations' ),
		"Enable Comments" => __( "Enable Comments", 'genesis-translations' ),
		"on posts?" => __( "on posts?", 'genesis-translations' ),
		"on pages?" => __( "on pages?", 'genesis-translations' ),
		"Enable Trackbacks" => __( "Enable Trackbacks", 'genesis-translations' ),
		"Display" => __( "Display", 'genesis-translations' ),
		"Entry content" => __( "Entry content", 'genesis-translations' ),
		"Entry excerpts" => __( "Entry excerpts", 'genesis-translations' ),
		"Limit content to" => __( "Limit content to", 'genesis-translations' ),
		"characters" => __( "characters", 'genesis-translations' ),
		"Featured Image" => __( "Featured Image", 'genesis-translations' ),
		"Include the Featured Image?" => __( "Include the Featured Image?", 'genesis-translations' ),
		"Image Size:" => __( "Image Size:", 'genesis-translations' ),
		"Image Alignment:" => __( "Image Alignment:", 'genesis-translations' ),
		"Entry Pagination" => __( "Entry Pagination", 'genesis-translations' ),
		"These settings apply to any page given the \"Blog\" page template, not the homepage or post archive pages." => __( "These settings apply to any page given the \"Blog\" page template, not the homepage or post archive pages.", 'genesis-translations' ),
		"Display Category" => __( "Display Category", 'genesis-translations' ),
		"Display which category:" => __( "Display which category:", 'genesis-translations' ),
		"All Categories" => __( "All Categories", 'genesis-translations' ),
		"Exclude Categories" => __( "Exclude Categories", 'genesis-translations' ),
		"Category IDs, comma separated - 1,2,3 for example" => __( "Category IDs, comma separated - 1,2,3 for example", 'genesis-translations' ),
		"Posts per Page" => __( "Posts per Page", 'genesis-translations' ),
		"Header Scripts" => __( "Header Scripts", 'genesis-translations' ),
		"This code will output immediately before the closing %s tag in the document source." => __( "This code will output immediately before the closing %s tag in the document source.", 'genesis-translations' ),
		"Footer Scripts" => __( "Footer Scripts", 'genesis-translations' ),
		"Google+" => __( "Google+", 'genesis-translations' ),
		"User Permissions" => __( "User Permissions", 'genesis-translations' ),
		"Genesis Admin Menus" => __( "Genesis Admin Menus", 'genesis-translations' ),
		"Enable Genesis Admin Menu?" => __( "Enable Genesis Admin Menu?", 'genesis-translations' ),
		"Enable SEO Settings Submenu?" => __( "Enable SEO Settings Submenu?", 'genesis-translations' ),
		"Enable Import/Export Submenu?" => __( "Enable Import/Export Submenu?", 'genesis-translations' ),
		"Author Archive Settings" => __( "Author Archive Settings", 'genesis-translations' ),
		"These settings apply to this author's archive pages." => __( "These settings apply to this author's archive pages.", 'genesis-translations' ),
		"Custom Archive Headline" => __( "Custom Archive Headline", 'genesis-translations' ),
		"Will display in the %s tag at the top of the first page" => __( "Will display in the %s tag at the top of the first page", 'genesis-translations' ),
		"Custom Description Text" => __( "Custom Description Text", 'genesis-translations' ),
		"This text will be the first paragraph, and display on the first page" => __( "This text will be the first paragraph, and display on the first page", 'genesis-translations' ),
		"Author Box" => __( "Author Box", 'genesis-translations' ),
		"Enable Author Box on this User's Posts?" => __( "Enable Author Box on this User's Posts?", 'genesis-translations' ),
		"Enable Author Box on this User's Archives?" => __( "Enable Author Box on this User's Archives?", 'genesis-translations' ),
		"Author Archive SEO Settings" => __( "Author Archive SEO Settings", 'genesis-translations' ),
		"Welcome to Genesis %s" => __( "Welcome to Genesis %s", 'genesis-translations' ),
		"Congratulations! You're now running Genesis %s." => __( "Congratulations! You're now running Genesis %s.", 'genesis-translations' ),
		"What&#8217;s New" => __( "What&#8217;s New", 'genesis-translations' ),
		"Accessibility" => __( "Accessibility", 'genesis-translations' ),
		"Child themes now have the ability to turn on accessibility features like special text for screen readers, accessible search forms, consistent page and section headings, skip links, and an accessible drop-down navigation menu." => __( "Child themes now have the ability to turn on accessibility features like special text for screen readers, accessible search forms, consistent page and section headings, skip links, and an accessible drop-down navigation menu.", 'genesis-translations' ),
		"Schema.org Microdata Improvements" => __( "Schema.org Microdata Improvements", 'genesis-translations' ),
		"Genesis continues to improve its implementation of Schema.org microdata in our markup, now including breadcrumb microdata." => __( "Genesis continues to improve its implementation of Schema.org microdata in our markup, now including breadcrumb microdata.", 'genesis-translations' ),
		"WordPress Feature Compatibility" => __( "WordPress Feature Compatibility", 'genesis-translations' ),
		"WordPress recently included support for generated title tags, as well as adding support for uploading a custom site icon, and now Genesis is compatible with both new features." => __( "WordPress recently included support for generated title tags, as well as adding support for uploading a custom site icon, and now Genesis is compatible with both new features.", 'genesis-translations' ),
		"Project Leads" => __( "Project Leads", 'genesis-translations' ),
		"Lead Developer" => __( "Lead Developer", 'genesis-translations' ),
		"Contributors" => __( "Contributors", 'genesis-translations' ),
		"Contributor" => __( "Contributor", 'genesis-translations' ),
		"Go to Theme Settings &rarr;" => __( "Go to Theme Settings &rarr;", 'genesis-translations' ),
		"Go to SEO Settings &rarr;" => __( "Go to SEO Settings &rarr;", 'genesis-translations' ),
		"You cannot use %s to create two menus in the same subclass. Please use separate subclasses for each menu." => __( "You cannot use %s to create two menus in the same subclass. Please use separate subclasses for each menu.", 'genesis-translations' ),
		"Home" => __( "Home", 'genesis-translations' ),
		" <span aria-label=\"breadcrumb separator\">/</span> " => __( " <span aria-label=\"breadcrumb separator\">/</span> ", 'genesis-translations' ),
		"You are here: " => __( "You are here: ", 'genesis-translations' ),
		"Archives for " => __( "Archives for ", 'genesis-translations' ),
		"Search for " => __( "Search for ", 'genesis-translations' ),
		"Not found: " => __( "Not found: ", 'genesis-translations' ),
		"Genesis database upgraded." => __( "Genesis database upgraded.", 'genesis-translations' ),
		'The argument, \"context\", has been replaced with \"theme_location\" in the $args array.' => __( 'The argument, \"context\", has been replaced with \"theme_location\" in the $args array.', 'genesis-translations' ),
		"data in style sheet files" => __( "data in style sheet files", 'genesis-translations' ),
		"decimal or hexidecimal entities" => __( "decimal or hexidecimal entities", 'genesis-translations' ),
		"about " => __( "about ", 'genesis-translations' ),
		"Pages:" => __( "Pages:", 'genesis-translations' ),
		"Categories:" => __( "Categories:", 'genesis-translations' ),
		"Authors:" => __( "Authors:", 'genesis-translations' ),
		"Monthly:" => __( "Monthly:", 'genesis-translations' ),
		"Recent Posts:" => __( "Recent Posts:", 'genesis-translations' ),
		"Content, Primary Sidebar" => __( "Content, Primary Sidebar", 'genesis-translations' ),
		"Primary Sidebar, Content" => __( "Primary Sidebar, Content", 'genesis-translations' ),
		"Content, Primary Sidebar, Secondary Sidebar" => __( "Content, Primary Sidebar, Secondary Sidebar", 'genesis-translations' ),
		"Secondary Sidebar, Primary Sidebar, Content" => __( "Secondary Sidebar, Primary Sidebar, Content", 'genesis-translations' ),
		"Secondary Sidebar, Content, Primary Sidebar" => __( "Secondary Sidebar, Content, Primary Sidebar", 'genesis-translations' ),
		"No Label Selected" => __( "No Label Selected", 'genesis-translations' ),
		"Primary Sidebar" => __( "Primary Sidebar", 'genesis-translations' ),
		"Secondary Sidebar" => __( "Secondary Sidebar", 'genesis-translations' ),
		"Main navigation" => __( "Main navigation", 'genesis-translations' ),
		"Have you tried our Scribe content marketing software? Do research, content and website optimization, and relationship building without leaving WordPress. <strong>Genesis owners save big when using the special link on the special page we've created just for you</strong>. <a href=\"%s\" target=\"_blank\">Click here for more info on Scribe<span class=\"screen-reader-text\">. %s</span></a>." => __( "Have you tried our Scribe content marketing software? Do research, content and website optimization, and relationship building without leaving WordPress. <strong>Genesis owners save big when using the special link on the special page we've created just for you</strong>. <a href=\"%s\" target=\"_blank\">Click here for more info on Scribe<span class=\"screen-reader-text\">. %s</span></a>.", 'genesis-translations' ),
		"Dismiss" => __( "Dismiss", 'genesis-translations' ),
		"Congratulations, you are now rocking Genesis %s! <a href=\"%s\">See what's new in %s</a>." => __( "Congratulations, you are now rocking Genesis %s! <a href=\"%s\">See what's new in %s</a>.", 'genesis-translations' ),
		"Click here to complete the upgrade" => __( "Click here to complete the upgrade", 'genesis-translations' ),
		"Genesis %s is available. <a href=\"%s\" %s>Check out what's new</a> or <a href=\"%s\" %s>update now.</a>" => __( "Genesis %s is available. <a href=\"%s\" %s>Check out what's new</a> or <a href=\"%s\" %s>update now.</a>", 'genesis-translations' ),
		"Genesis %s is available for %s" => __( "Genesis %s is available for %s", 'genesis-translations' ),
		"Genesis %s is now available. We have provided 1-click updates for this theme, so please log into your dashboard and update at your earliest convenience." => __( "Genesis %s is now available. We have provided 1-click updates for this theme, so please log into your dashboard and update at your earliest convenience.", 'genesis-translations' ),
		"Header Left" => __( "Header Left", 'genesis-translations' ),
		"Header Right" => __( "Header Right", 'genesis-translations' ),
		"This is the header widget area. It typically appears next to the site title or logo. This widget area is not suitable to display every type of widget, and works best with a custom menu, a search form, or possibly a text widget." => __( "This is the header widget area. It typically appears next to the site title or logo. This widget area is not suitable to display every type of widget, and works best with a custom menu, a search form, or possibly a text widget.", 'genesis-translations' ),
		"This is the primary sidebar if you are using a two or three column site layout option." => __( "This is the primary sidebar if you are using a two or three column site layout option.", 'genesis-translations' ),
		"This is the secondary sidebar if you are using a three column site layout option." => __( "This is the secondary sidebar if you are using a three column site layout option.", 'genesis-translations' ),
		"Footer %d" => __( "Footer %d", 'genesis-translations' ),
		"Footer %d widget area." => __( "Footer %d widget area.", 'genesis-translations' ),
		"After Entry" => __( "After Entry", 'genesis-translations' ),
		"Widgets in this widget area will display after single entries." => __( "Widgets in this widget area will display after single entries.", 'genesis-translations' ),
		"Primary Navigation Menu" => __( "Primary Navigation Menu", 'genesis-translations' ),
		"Secondary Navigation Menu" => __( "Secondary Navigation Menu", 'genesis-translations' ),
		"Select / Deselect All" => __( "Select / Deselect All", 'genesis-translations' ),
		"The changes you made will be lost if you navigate away from this page." => __( "The changes you made will be lost if you navigate away from this page.", 'genesis-translations' ),
		"Updating Genesis will overwrite the current installed version of Genesis. Are you sure you want to update?. \"Cancel\" to stop, \"OK\" to update." => __( "Updating Genesis will overwrite the current installed version of Genesis. Are you sure you want to update?. \"Cancel\" to stop, \"OK\" to update.", 'genesis-translations' ),
		"Are you sure you want to reset?" => __( "Are you sure you want to reset?", 'genesis-translations' ),
		"Return to top of page" => __( "Return to top of page", 'genesis-translations' ),
		"by" => __( "by", 'genesis-translations' ),
		"Log in" => __( "Log in", 'genesis-translations' ),
		"Log out" => __( "Log out", 'genesis-translations' ),
		"ago" => __( "ago", 'genesis-translations' ),
		"% Comments" => __( "% Comments", 'genesis-translations' ),
		"1 Comment" => __( "1 Comment", 'genesis-translations' ),
		"Leave a Comment" => __( "Leave a Comment", 'genesis-translations' ),
		"Tagged With: " => __( "Tagged With: ", 'genesis-translations' ),
		"Filed Under: " => __( "Filed Under: ", 'genesis-translations' ),
		"(Edit)" => __( "(Edit)", 'genesis-translations' ),
		"<h3>Comments</h3>" => __( "<h3>Comments</h3>", 'genesis-translations' ),
		"<h3>Trackbacks</h3>" => __( "<h3>Trackbacks</h3>", 'genesis-translations' ),
		"<cite class=\"fn\">%s</cite> <span class=\"says\">%s:</span>" => __( "<cite class=\"fn\">%s</cite> <span class=\"says\">%s:</span>", 'genesis-translations' ),
		"says" => __( "says", 'genesis-translations' ),
		'%1$s at %2$s' => __( '%1$s at %2$s', 'genesis-translations' ),
		"Your comment is awaiting moderation." => __( "Your comment is awaiting moderation.", 'genesis-translations' ),
		"at" => __( "at", 'genesis-translations' ),
		"Name" => __( "Name", 'genesis-translations' ),
		"Email" => __( "Email", 'genesis-translations' ),
		"Website" => __( "Website", 'genesis-translations' ),
		"Speak Your Mind" => __( "Speak Your Mind", 'genesis-translations' ),
		"Copyright" => __( "Copyright", 'genesis-translations' ),
		"on" => __( "on", 'genesis-translations' ),
		"Skip to primary navigation" => __( "Skip to primary navigation", 'genesis-translations' ),
		"Skip to content" => __( "Skip to content", 'genesis-translations' ),
		"Skip to primary sidebar" => __( "Skip to primary sidebar", 'genesis-translations' ),
		"Skip to secondary sidebar" => __( "Skip to secondary sidebar", 'genesis-translations' ),
		"Skip to footer" => __( "Skip to footer", 'genesis-translations' ),
		"Skip links" => __( "Skip links", 'genesis-translations' ),
		"Read more" => __( "Read more", 'genesis-translations' ),
		"Posts" => __( "Posts", 'genesis-translations' ),
		"Comments" => __( "Comments", 'genesis-translations' ),
		"[Read more...]" => __( "[Read more...]", 'genesis-translations' ),
		"Sorry, no content matched your criteria." => __( "Sorry, no content matched your criteria.", 'genesis-translations' ),
		"About" => __( "About", 'genesis-translations' ),
		"Previous Page" => __( "Previous Page", 'genesis-translations' ),
		"Next Page" => __( "Next Page", 'genesis-translations' ),
		"Page " => __( "Page ", 'genesis-translations' ),
		"Current page" => __( "Current page", 'genesis-translations' ),
		"Search this website" => __( "Search this website", 'genesis-translations' ),
		"Search" => __( "Search", 'genesis-translations' ),
		"Primary Sidebar Widget Area" => __( "Primary Sidebar Widget Area", 'genesis-translations' ),
		"Secondary Sidebar Widget Area" => __( "Secondary Sidebar Widget Area", 'genesis-translations' ),
		"This is the %s. You can add content to this area by visiting your <a href=\"%s\">Widgets Panel</a> and adding new widgets to this area." => __( "This is the %s. You can add content to this area by visiting your <a href=\"%s\">Widgets Panel</a> and adding new widgets to this area.", 'genesis-translations' ),
		"Displays featured page with thumbnails" => __( "Displays featured page with thumbnails", 'genesis-translations' ),
		"Genesis - Featured Page" => __( "Genesis - Featured Page", 'genesis-translations' ),
		"(no title)" => __( "(no title)", 'genesis-translations' ),
		"Title" => __( "Title", 'genesis-translations' ),
		"Page" => __( "Page", 'genesis-translations' ),
		"Show Featured Image" => __( "Show Featured Image", 'genesis-translations' ),
		"Image Size" => __( "Image Size", 'genesis-translations' ),
		"Image Alignment" => __( "Image Alignment", 'genesis-translations' ),
		"Center" => __( "Center", 'genesis-translations' ),
		"Show Page Title" => __( "Show Page Title", 'genesis-translations' ),
		"Show Page Content" => __( "Show Page Content", 'genesis-translations' ),
		"Content Character Limit" => __( "Content Character Limit", 'genesis-translations' ),
		"More Text" => __( "More Text", 'genesis-translations' ),
		"By" => __( "By", 'genesis-translations' ),
		"[Read More...]" => __( "[Read More...]", 'genesis-translations' ),
		"More Posts from this Category" => __( "More Posts from this Category", 'genesis-translations' ),
		"Displays featured posts with thumbnails" => __( "Displays featured posts with thumbnails", 'genesis-translations' ),
		"Genesis - Featured Posts" => __( "Genesis - Featured Posts", 'genesis-translations' ),
		"Category" => __( "Category", 'genesis-translations' ),
		"Number of Posts to Show" => __( "Number of Posts to Show", 'genesis-translations' ),
		"Number of Posts to Offset" => __( "Number of Posts to Offset", 'genesis-translations' ),
		"Order By" => __( "Order By", 'genesis-translations' ),
		"Date" => __( "Date", 'genesis-translations' ),
		"Parent" => __( "Parent", 'genesis-translations' ),
		"ID" => __( "ID", 'genesis-translations' ),
		"Comment Count" => __( "Comment Count", 'genesis-translations' ),
		"Random" => __( "Random", 'genesis-translations' ),
		"Sort Order" => __( "Sort Order", 'genesis-translations' ),
		"Descending (3, 2, 1)" => __( "Descending (3, 2, 1)", 'genesis-translations' ),
		"Ascending (1, 2, 3)" => __( "Ascending (1, 2, 3)", 'genesis-translations' ),
		"Exclude Previously Displayed Posts?" => __( "Exclude Previously Displayed Posts?", 'genesis-translations' ),
		"Exclude Sticky Posts?" => __( "Exclude Sticky Posts?", 'genesis-translations' ),
		"Show Author Gravatar" => __( "Show Author Gravatar", 'genesis-translations' ),
		"Gravatar Size" => __( "Gravatar Size", 'genesis-translations' ),
		"Small (45px)" => __( "Small (45px)", 'genesis-translations' ),
		"Medium (65px)" => __( "Medium (65px)", 'genesis-translations' ),
		"Large (85px)" => __( "Large (85px)", 'genesis-translations' ),
		"Extra Large (125px)" => __( "Extra Large (125px)", 'genesis-translations' ),
		"Gravatar Alignment" => __( "Gravatar Alignment", 'genesis-translations' ),
		"Show Post Title" => __( "Show Post Title", 'genesis-translations' ),
		"Show Post Info" => __( "Show Post Info", 'genesis-translations' ),
		"Content Post Info" => __( "Content Post Info", 'genesis-translations' ),
		"Content Type" => __( "Content Type", 'genesis-translations' ),
		"Show Content" => __( "Show Content", 'genesis-translations' ),
		"Show Excerpt" => __( "Show Excerpt", 'genesis-translations' ),
		"Show Content Limit" => __( "Show Content Limit", 'genesis-translations' ),
		"No Content" => __( "No Content", 'genesis-translations' ),
		"More Text (if applicable)" => __( "More Text (if applicable)", 'genesis-translations' ),
		"To display an unordered list of more posts from this category, please fill out the information below" => __( "To display an unordered list of more posts from this category, please fill out the information below", 'genesis-translations' ),
		"Show Category Archive Link" => __( "Show Category Archive Link", 'genesis-translations' ),
		"Link Text" => __( "Link Text", 'genesis-translations' ),
		"Read More" => __( "Read More", 'genesis-translations' ),
		"Displays user profile block with Gravatar" => __( "Displays user profile block with Gravatar", 'genesis-translations' ),
		"Genesis - User Profile" => __( "Genesis - User Profile", 'genesis-translations' ),
		"View My Blog Posts" => __( "View My Blog Posts", 'genesis-translations' ),
		"Select a user. The email address for this account will be used to pull the Gravatar image." => __( "Select a user. The email address for this account will be used to pull the Gravatar image.", 'genesis-translations' ),
		"Small" => __( "Small", 'genesis-translations' ),
		"Medium" => __( "Medium", 'genesis-translations' ),
		"Large" => __( "Large", 'genesis-translations' ),
		"Extra Large" => __( "Extra Large", 'genesis-translations' ),
		"Select which text you would like to use as the author description" => __( "Select which text you would like to use as the author description", 'genesis-translations' ),
		"Author Bio" => __( "Author Bio", 'genesis-translations' ),
		"Custom Text (below)" => __( "Custom Text (below)", 'genesis-translations' ),
		"Custom Text Content" => __( "Custom Text Content", 'genesis-translations' ),
		"Choose your extended \"About Me\" page from the list below. This will be the page linked to at the end of the about me section." => __( "Choose your extended \"About Me\" page from the list below. This will be the page linked to at the end of the about me section.", 'genesis-translations' ),
		"Extended page link text" => __( "Extended page link text", 'genesis-translations' ),
		"Show Author Archive Link?" => __( "Show Author Archive Link?", 'genesis-translations' ),
		"Search Results for:" => __( "Search Results for:", 'genesis-translations' ),
		"Genesis" => __( "Genesis", 'genesis-translations' ),
		"http://my.studiopress.com/themes/genesis/" => __( "http://my.studiopress.com/themes/genesis/", 'genesis-translations' ),
		"The industry standard for Premium WordPress Themes. Please do not modify this style sheet, as it might get overridden in updates." => __( "The industry standard for Premium WordPress Themes. Please do not modify this style sheet, as it might get overridden in updates.", 'genesis-translations' ),
		"StudioPress" => __( "StudioPress", 'genesis-translations' ),
		"http://www.studiopress.com/" => __( "http://www.studiopress.com/", 'genesis-translations' ),
		"Blog" => __( "Blog", 'genesis-translations' ),
		"seconds" => __( "seconds", 'genesis-translations' ),
		'%s year-%s years' => _nx_noop( '%s year', '%s years', 'time difference', 'genesis-translations' ),
		'%s month-%s months' => _nx_noop( '%s month', '%s months', 'time difference', 'genesis-translations' ),
		'%s week-%s weeks' => _nx_noop( '%s week', '%s weeks', 'time difference', 'genesis-translations' ),
		'%s day-%s days' => _nx_noop( '%s day', '%s days', 'time difference', 'genesis-translations' ),
		'%s hour-%s hours' => _nx_noop( '%s hour', '%s hours', 'time difference', 'genesis-translations' ),
		'%s minute-%s minutes' => _nx_noop( '%s minute', '%s minutes', 'time difference', 'genesis-translations' ),
		'%s second-%s seconds' => _nx_noop( '%s second', '%s seconds', 'time difference', 'genesis-translations' ),
		"and" => __( "and", 'genesis-translations' ),

	);
}

//add_filter( 'gettext', 'thememix_genesis_translations_gettext_filter', 10, 3 );
/**
 * Translating items.
 *
 * @param  string  $text        The text
 * @param  string  $text_domain The original text
 * @param  string  $text_domain The text domain
 * @return string  The translated text
 */
function thememix_genesis_translations_gettext_filter( $text, $text_string, $text_domain ) {

	if ( 'genesis' == $text_domain ) {
		$translations = thememix_genesis_translations_strings();
		if ( isset( $translations[$text_string] ) ) {
			return $translations[$text_string];
		}
	}

	return $text;
}


add_filter( 'ngettext_with_context', 'thememix_genesis_translations_gettext_with_context_filter', 10, 6 );
/**
 * Translating plauralised items.
 *
 * @param  string  $text        The translated text
 * @param  string  $singular    The singular text
 * @param  string  $plaural     The plaural text
 * @param  int     $count       The number of objects
 * @param  string  $context     The translation context
 * @param  string  $text_domain The text domain
 * @return string  The translated text
 */
function thememix_genesis_translations_gettext_with_context_filter( $text, $singular, $plaural, $count, $context, $text_domain ) {

	if ( 'genesis' == $text_domain ) {
		$translations = thememix_genesis_translations_strings();

		if ( 1 < $count && isset( $translations[$plaural] ) ) {
			return $translations[$plaural];
		} elseif ( 2 > $count && isset( $translations[$singular] ) ) {
			return $translations[$singular];
		}

	}

	return $text;
}


